In [1]:
import numpy as np
import pandas as pd
import scipy
from scipy import integrate

In [2]:
# Returns probability transition matrix
def prob_transition_matrix(adj,alpha):
  N = len(adj)
  empty_rows = list(np.where(~adj.any(axis=1))[0])
  for i in empty_rows:
    for j in range(0,N):
      adj[i][j] = 1/N
  
  prob_matrix = adj/adj.sum(axis=1,keepdims=True)
  prob_matrix = prob_matrix * (1-alpha)
  prob_matrix = prob_matrix + alpha/N 

  return prob_matrix

In [37]:
# TAKE INPUT WEB-GRAPH
N = int(input("Enter number of nodes : "))
e = int(input("Enter number of edges : "))
adj = np.zeros([N,N])
for i in range(0,e):
  lst = list(map(int,input().split()))
  u = lst[0]
  v = lst[1]
  adj[u,v] = 1

adj

Enter number of nodes : 4
Enter number of edges : 6
0 1
1 0
1 2
2 1
2 3
3 2


array([[0., 1., 0., 0.],
       [1., 0., 1., 0.],
       [0., 1., 0., 1.],
       [0., 0., 1., 0.]])

# **PAGE - RANK IMPLEMENTATION WITH LINEAR ALGEBRA PACKAGE**




## 1. Without random teleportation (alpha = 0)



In [38]:
prob_matrix=prob_transition_matrix(adj,0) 
prob_matrix

array([[0. , 1. , 0. , 0. ],
       [0.5, 0. , 0.5, 0. ],
       [0. , 0.5, 0. , 0.5],
       [0. , 0. , 1. , 0. ]])

In [39]:
left_eigen_vector = scipy.linalg.eig(prob_matrix,left=True,right=False)[1][:,0]
left_eigen_vector = abs(left_eigen_vector / np.sum(left_eigen_vector))
left_eigen_vector

array([5.17877545e+14, 1.03575509e+15, 1.03575509e+15, 5.17877545e+14])

In [40]:
print("Web pages according to rank (largest to smallest) : ")
list((-left_eigen_vector).argsort()[:N])

Web pages according to rank (largest to smallest) : 


[2, 1, 3, 0]

## 2. With random teleportation (alpha = 0.1)

In [41]:
prob_matrix=prob_transition_matrix(adj,0.1) 
prob_matrix

array([[0.025, 0.925, 0.025, 0.025],
       [0.475, 0.025, 0.475, 0.025],
       [0.025, 0.475, 0.025, 0.475],
       [0.025, 0.025, 0.925, 0.025]])

In [42]:
left_eigen_vector = scipy.linalg.eig(prob_matrix,left=True,right=False)[1][:,0]
left_eigen_vector = abs(left_eigen_vector / np.sum(left_eigen_vector))
left_eigen_vector

array([0.17241379, 0.32758621, 0.32758621, 0.17241379])

In [43]:
print("Web pages according to rank (largest to smallest) : ")
list((-left_eigen_vector).argsort()[:N])

Web pages according to rank (largest to smallest) : 


[2, 1, 0, 3]

# **PAGE - RANK IMPLEMENTATION WITH POWER ITERATION METHOD**


## 1. Without random teleportation (alpha = 0)
## 2. With random teleportation (alpha = 0.1)

In [47]:
# Consider random-surfer starts from state 0
# Initial prob_dist vector : [1,0,0,.......]
x = np.zeros(N)
x[0]=1
P = prob_transition_matrix(adj,0.1)
curr_vec = x
prev_vec = np.ones(N)
cou=0
while True :
  print("x"+str(cou)+":"+str(curr_vec))
  curr_vec = x@P
  if (str(curr_vec) == str(prev_vec)):
    break
  prev_vec = curr_vec
  x = curr_vec
  cou+=1

print("Converged steady state vector : ")
final_prob_vect = curr_vec
final_prob_vect

x0:[1. 0. 0. 0.]
x1:[0.025 0.925 0.025 0.025]
x2:[0.44125 0.05875 0.46375 0.03625]
x3:[0.0514375 0.6308125 0.0840625 0.2336875]
x4:[0.30886563 0.10912188 0.51918438 0.06282813]
x5:[0.07410484 0.53661203 0.13065016 0.25863297]
x6:[0.26647541 0.15048693 0.49924509 0.08379257]
x7:[0.09271912 0.48948816 0.16813243 0.24966029]
x8:[0.24526967 0.1841068  0.46996393 0.10065959]
x9:[0.10784806 0.45722647 0.1984417  0.23648377]
x10:[0.23075191 0.21136202 0.44358731 0.11429876]
x11:[0.12011291 0.43229101 0.22298179 0.22461429]
x12:[0.21953095 0.23344342 0.42168381 0.12534181]
x13:[0.13004954 0.41233558 0.24285717 0.21475772]
x14:[0.21055101 0.25133031 0.40383295 0.13428573]
x15:[0.13809864 0.39622074 0.25895579 0.20672483]
x16:[0.20329933 0.26581888 0.38935168 0.14153011]
x17:[0.1446185  0.38317765 0.27199559 0.20020826]
x18:[0.19742994 0.27755467 0.37761737 0.14739802]
x19:[0.1498996  0.37261477 0.28255781 0.19492782]
x20:[0.19267665 0.28706066 0.36811168 0.15215102]
x21:[0.1541773  0.36405924 0

array([0.17241379, 0.32758621, 0.32758621, 0.17241379])

In [48]:
# Ranking the web pages 
print("Web pages according to rank (largest to smallest) : ")
list((-final_prob_vect).argsort()[:N])

Web pages according to rank (largest to smallest) : 


[2, 1, 0, 3]